/**
 * Type inference utilities for extracting Document, Insert, and Update types from schemas
 */

// import type { ObjectId } from 'mongodb'; // Will be used for filter types later
import type { AnyFieldBuilder, SchemaDefinition, InferFieldBuilderType } from './field';

/**
 * Infer the base TypeScript type from a field builder
 */
export type InferFieldType<T extends AnyFieldBuilder> = InferFieldBuilderType<T>;

/**
 * Extract schema from a CollectionDefinition or use SchemaDefinition directly
 */
export type ExtractSchemaOrUse<T> = T extends { _schema: infer S extends SchemaDefinition }
  ? S
  : T extends SchemaDefinition
    ? T
    : never;

/**
 * Infer the full document type from a schema definition or collection definition
 * This represents what you get when reading from the database
 */
export type InferDocument<T> = {
  [K in keyof ExtractSchemaOrUse<T>]: InferFieldType<ExtractSchemaOrUse<T>[K]>;
};

/**
 * Helper to check if a field is optional
 * Now checks the type-level _configState instead of runtime _config
 */
type IsOptional<T extends AnyFieldBuilder> = T extends { _configState: { optional: true } }
  ? true
  : false;

/**
 * Helper to check if a field has a default value
 * Now checks the type-level _configState for hasDefault or hasDefaultNow
 */
type HasDefault<T extends AnyFieldBuilder> = T extends {
  _configState: { hasDefault: true };
}
  ? true
  : T extends { _configState: { hasDefaultNow: true } }
    ? true
    : false;

/**
 * Helper to check if a field is auto-generated (like _id or publicId)
 * Now checks the type-level _configState for isInternalId or isPublicId
 */
type IsAutoGenerated<T extends AnyFieldBuilder> = T extends {
  _configState: { isInternalId: true };
}
  ? true
  : T extends { _configState: { isPublicId: true } }
    ? true
    : false;

/**
 * Fields required for insert (no defaults, not auto-generated, not optional)
 */
type RequiredInsertFields<T> = {
  [K in keyof ExtractSchemaOrUse<T>]: IsAutoGenerated<ExtractSchemaOrUse<T>[K]> extends true
    ? never
    : HasDefault<ExtractSchemaOrUse<T>[K]> extends true
      ? never
      : IsOptional<ExtractSchemaOrUse<T>[K]> extends true
        ? never
        : K;
}[keyof ExtractSchemaOrUse<T>];

/**
 * Fields optional for insert (have defaults or are optional or auto-generated)
 */
type OptionalInsertFields<T> = {
  [K in keyof ExtractSchemaOrUse<T>]: IsAutoGenerated<ExtractSchemaOrUse<T>[K]> extends true
    ? K
    : HasDefault<ExtractSchemaOrUse<T>[K]> extends true
      ? K
      : IsOptional<ExtractSchemaOrUse<T>[K]> extends true
        ? K
        : never;
}[keyof ExtractSchemaOrUse<T>];

/**
 * Infer the insert type from a schema definition or collection definition
 * This represents what you pass when creating a new document
 */
export type InferInsert<T> = Pick<InferDocument<T>, RequiredInsertFields<T>> &
  Partial<Pick<InferDocument<T>, OptionalInsertFields<T>>>;

/**
 * Infer the update type from a schema definition or collection definition
 * This represents what you can pass when updating a document
 * All fields are optional for updates
 */
export type InferUpdate<T> = Partial<Omit<InferDocument<T>, '_id'>>;

/**
 * Utility type to extract schema from a collection definition
 */
export type ExtractSchema<T> = T extends { _schema: infer S extends SchemaDefinition } ? S : never;

/**
 * MongoDB filter type (simplified)
 */
export type Filter<T> = {
  [K in keyof T]?: T[K] | FilterOperators<T[K]>;
} & {
  $and?: Filter<T>[];
  $or?: Filter<T>[];
  $nor?: Filter<T>[];
};

/**
 * MongoDB filter operators
 */
export type FilterOperators<T> = {
  $eq?: T;
  $ne?: T;
  $gt?: T;
  $gte?: T;
  $lt?: T;
  $lte?: T;
  $in?: T[];
  $nin?: T[];
  $exists?: boolean;
  $regex?: RegExp | string;
  $options?: string;
};

/**
 * MongoDB update operators
 */
export type UpdateOperators<T> = {
  $set?: Partial<T>;
  $unset?: { [K in keyof T]?: '' | 1 | true };
  $inc?: { [K in keyof T]?: number };
  $mul?: { [K in keyof T]?: number };
  $rename?: { [K in keyof T]?: string };
  $min?: Partial<T>;
  $max?: Partial<T>;
  $currentDate?: {
    [K in keyof T]?: true | { $type: 'date' | 'timestamp' };
  };
  $push?: any;
  $pull?: any;
  $addToSet?: any;
  $pop?: any;
};

/**
 * Sort direction
 */
export type SortDirection = 1 | -1 | 'asc' | 'desc';

/**
 * Sort specification
 */
export type Sort<T> = {
  [K in keyof T]?: SortDirection;
};

/**
 * Projection specification
 */
export type Projection<T> = {
  [K in keyof T]?: 0 | 1 | boolean;
};

/**
 * Find options
 */
export interface FindOptions<T> {
  sort?: Sort<T>;
  limit?: number;
  skip?: number;
  projection?: Projection<T>;
}

/**
 * Find many result with pagination info
 */
export interface FindManyResult<T> {
  data: T[];
  hasMore: boolean;
  total?: number;
}
